leaf:
  name: info.bonian.leaf
  segment:
    enable: false
    url: jdbc:mysql://192.168.2.101/leaf?serverTimezone=GMT%2B8
    username: root
    password: toor

  snowflake:
    enable: false
    port: 2181
    zk:
      address: 192.168.2.101